### ISSUE TITLE
Console Command to Join Players to a Queue

### ISSUE THREAD

**Issue by Starmism** [ajgeiss0702/ajQueue#14]
A common use case for servers is using console commands or some other elevated command executor to do things to players. A big one for us involves using NPCs from BetonQuest and Citizens to move people between servers. We ended up implementing our own version of this, a so-called `cqueue` command (console-queue), but also made a few breaking changes on the way for Java 17 and formatting, etc. 

That fork can be found [here](https://github.com/valence-smp/ajQueue).

**Comment by ajgeiss0702** [comment]
This is already a feature
