### ISSUE TITLE
Add custom max-tries value for specific server OR if stated in the command

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [ajgeiss0702/ajQueue#22]
Basically what the title says

**OPTION 1** - *custom max-tries value for specific server*
```yml
max-tries:
  default: 10 # set -1 to disable or 0 for forever
  authlobby1: 0
```
also, making that `0` will mean that it will try to send player until it either successfully sends it (if for example server was offline/restarting and has gone back online), player manually leaves the queue (by executing his own command), or he leaves the server (network)

**OPTION 2** - *state specifically in the command*
e.g. `/ajqueue send TestPlayer hub -t50` where `-t50` will mean *try 50 times until successful*
or `/ajqueue send TestPlayer hub -f` where `-f` will mean *try forever until successful* or until server closes/player leaves the server or the queue manually

* NOTE (for option 2): for this, making sure that ajQueue has this on spigot side to so we can also execute from spigot console `/server TestPlayer hub -f` to try sending TestPlayer to hub server *trying forever until successful*.....

**Comment by MotikaCraft-TheJoshua** [comment]
weird thing i realized is that even with `max-tries` on default (which is `10`), it will still *forever* to try and try again and again to send player to the target server if it's offline, if this is regular and this is intended - i would like a confirmation and this suggestion can be closed because it's obviously already a thing

**Comment by ajgeiss0702** [comment]
This is not the place for suggestions
