### ISSUE TITLE
ajQueue Cooldowns Memory Leak

### ISSUE THREAD

**Issue by R00tB33rMan** [ajgeiss0702/ajQueue#24]
Cooldowns appear to be initiating a severe memory leak; uptime is 23 hours as this heap is generated. Only ~230 players were online during this heap generation.

![image](https://user-images.githubusercontent.com/36140389/226408756-bfea8bb1-10f4-4fa8-80c1-5deeea87ac00.png)

My presumption is that user data isn't clearing after cache; overtime, building up memory usage excessively.

**Comment by ajgeiss0702** [comment]
This is not the place to get support
