### ISSUE TITLE
ajqueue could not detect backend servers.

### ISSUE THREAD

**Issue by hamza-cskn** [ajgeiss0702/ajQueue#25]
<img width="437" alt="resim" src="https://user-images.githubusercontent.com/36128276/228366055-caaff3de-d033-49cd-8e46-baac32b4ed4c.png">

I installed the ajqueue plugin on my lobby server and proxy server. but ajqueue never detects the skyblock-spawn server.

versions:
proxy: git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515
backend(lobby): 1.16.5 paper 794
ajqueue: v2.3.1

proxy configuration:
https://hastebin.com/share/xijozirude.makefile
backend configuration is same as default.

**Comment by ajgeiss0702** [comment]
This is not the place to get support
