### ISSUE TITLE
Folia support

### ISSUE THREAD

**Issue by Potothingi** [ajgeiss0702/ajQueue#28]
I hope someday this plugin will support Folia.
Folia isn't a stable release yet, so don't rush.

Currently, 'ProtocolLib, Vault, LuckPerms, PlaceholderAPI, EssentialsX, ViaVersion, ViaBackwards, CoreProtect, DiscordSRV, Chunky, Spark' plugins already support Folia, or Folia support is ready in pull requests.

https://docs.papermc.io/folia

**Comment by ajgeiss0702** [comment]
ajQueue is a proxy plugin. Folia is a server, not a proxy.

Once it's a little more mature, the ajQueue spigot-side will run on Folia, but that's at *least* a few months away.
